services:
    artistdb-go:
        container_name: artistdb-go
        image: artistdb-go
        build:
            context: .
            dockerfile: Dockerfile
        pull_policy: never
        ports:
            - "8080:8080"
        restart: unless-stopped
        volumes:
            - ./artists.txt:/app/artists.txt
            - ./avatar:/app/avatar
        environment:
            PORT: 8080
            IN_FILE: ./artists.txt
            AVATAR_DIR: ./avatar
